---@type table<string, fun(cutscene:WorldCutscene)>
local depths = {}

function depths.start(cutscene)
    Game.world.music:stop()
    local kris = cutscene:getCharacter("kris")
    local susie = cutscene:getCharacter("susie")
    cutscene:fadeOut(0, {global = true})
    cutscene:detachCamera()
    cutscene:detachFollowers()
    kris:setSprite("fell")
    susie:setSprite("fell")
    kris:setPosition(Game.world.map:getMarker("spawn"))
    susie:setPosition(Game.world.map:getMarker("susiespawn"))
    cutscene:wait(1)
    cutscene:fadeIn(0, {global = true})
    Assets.playSound("noise")
    cutscene:wait(1)
    cutscene:text("* Ughhh...[wait:5] the hell happened...?", "sad", susie)
    Assets.playSound("wing", 0.5)
    susie:shake()
    susie:setSprite("down")
    cutscene:text("* Kris...[wait:5] get up,[wait:5] Kris!!!!", "sad", susie)
    cutscene:wait(2)
    Assets.playSound("wing", 0.5)
    kris:shake()
    kris:setSprite("sit")
    cutscene:wait(1)
    cutscene:text("* Damn,[wait:5] looks like we made it to...[wait:5] some kind of dark world...?", "sad", susie)
    cutscene:text("* Let's get going,[wait:5] Kris,[wait:5] maybe Ralsei's here or something...", "sad", susie)
    cutscene:wait(1)
    susie:setAnimation({"down_happy", 0.4, next="walk"})
    kris:setAnimation({"landed", 0.4, next="walk"})
    cutscene:wait(2)
    kris:setFacing("up")
    susie:setFacing("down")
    Game.world.music:play("endless_expanse")

    kris:setFacing("down")
    cutscene:interpolateFollowers()
    cutscene:attachCamera()
    cutscene:wait(cutscene:attachFollowers())
end

return depths