return {

    device = function(cutscene)
		if Plot:isBefore("shelter_heard_log") then
			local kris = assert(cutscene:getCharacter("kris"))
			local susie = cutscene:getCharacter("susie") or kris
			local noelle = cutscene:getCharacter("noelle") or susie
			Kristal.Console:log("device_used")   
			cutscene:detachFollowers()
			local x, y = cutscene:getMarker("kris1")
			cutscene:walkTo(kris, x, y, 2, "left")
			local x, y = cutscene:getMarker("susie1")
			cutscene:walkTo(susie, x, y, 2, "left")
			local x, y = cutscene:getMarker("noelle1")
			cutscene:walkTo(noelle, x, y, 2, "left")
			cutscene:wait(2)
			kris:setFacing("left")
			susie:setFacing("up")
			noelle:setFacing("up")
			cutscene:setSpeaker("noelle")
			cutscene:text("* S-Susie?[wait:5] I...[wait:5] don't like the look of this device thingy...", "surprise_smile")
			cutscene:setSpeaker("susie")
			cutscene:text("* Neither do I...[wait:5] probably something important,[wait:5] though...", "neutral_side") 
			cutscene:text("* Guess we should check it out,[wait:5] just in case.", "neutral") 
			cutscene:text("* Let me just turn it on...", "nervous") 
			Assets.playSound("noise")
			cutscene:wait(0.5)
			cutscene:setSpeaker("voicemail")
			cutscene:text("[speed:0.5][color:green]> Loading...")
			cutscene:text("[speed:0.5][color:green]> Loading...")
			cutscene:text("[speed:0.5][color:green]> Loading...")
			cutscene:setSpeaker("susie")
			cutscene:text("* ...", "suspicious") 
			cutscene:wait(1.5)
			susie:setSprite("kick")
        	susie.sprite:play(0.1, loop)
			local rumble = Assets.playSound("impact")
			rumble:setLooping(true)
			cutscene:text("* GOD DAMNIT,[wait:5] MACHINE![wait:5]\n* JUST TURN ON ALREADY!!!!", "teeth") 
			cutscene:wait(1.5)
			cutscene:wait(0.5)
			cutscene:wait(1)
			cutscene:setSpeaker("voicemail")
			cutscene:text("[color:green]> POWERING ON SYSTEMS...")
			Assets.stopSound("impact")
			susie:resetSprite()
			cutscene:wait(0.7)
			cutscene:setSpeaker("susie")
			cutscene:text("* (Dang,[wait:5] did that actually work????)", "surprise") 
			cutscene:setSpeaker("voicemail")
			cutscene:text("[color:green]> STARTING MAIN USER INTERFACE...")
			cutscene:wait(cutscene:fadeOut(1.5))
			cutscene:wait(cutscene:gotoCutscene("deviceshelter.init"))
			cutscene:wait(cutscene:fadeIn(1.5, { music = true }))
			cutscene:setSpeaker(susie)
			cutscene:text("* Damn,[wait:5] so that thing was transmitting that we broke in here?", "neutral_side")
			cutscene:text("* Guess we can only hope nobody saw that...", "nervous_side")
			cutscene:text("* ... Otherwise,[wait:5] we might have a problem.", "sus_nervous")
			cutscene:setSpeaker("voicemail")
			cutscene:text("[color:red]> ERROR:[wait:5] POWER LEVEL AT 1%.\n> GATEWAY:[wait:5] UNSTABLE.")
			cutscene:text("[color:red]> TO PROTECT VITAL MACHINERY,[wait:5] POWERING OFF...")
			cutscene:setSpeaker(noelle)
			cutscene:text("* G-[wait:5]Gateway...?[wait:5] What does it mean a gateway is...[wait:5] unstable...?", "surprise_smile_b")
			cutscene:setSpeaker(susie)
			cutscene:text("* A gateway...[wait:5] if it's unstable,[wait:5] that cant be good,[wait:5] can it?", "sus_nervous")
			cutscene:text("* Could be what's causing the earthquakes,[wait:5] though...", "suspicious")
			cutscene:text("* ... let's go see if we can fix that Gateway,[wait:5] sound good,[wait:5] Kris?", "small_smile")
			SetPlot("shelter_heard_log")
			kris:walkTo(kris.x, kris.y + 20)
			cutscene:attachFollowers()
		end
    end,

	omnistime = function(cutscene)
		if Plot:isBefore("shelter_met_omnis") then
			local kris = assert(cutscene:getCharacter("kris"))
			local susie = cutscene:getCharacter("susie") or kris
			local noelle = cutscene:getCharacter("noelle") or susie
			Kristal.Console:log("device_used")   
			cutscene:detachFollowers()
			local x, y = cutscene:getMarker("susie1")
			cutscene:walkTo(susie, x, y, 2, "right")
			cutscene:wait(2)
			susie:setFacing("up")
			cutscene:setSpeaker("susie")
			cutscene:text("* Hey,[wait:5] guys![wait:5] Look over here!", "surprise_smile") 
			cutscene:wait(0.5)
			local x, y = cutscene:getMarker("kris1")
			cutscene:walkTo(kris, x, y, 1, "right")
			local x, y = cutscene:getMarker("noelle1")
			cutscene:walkTo(noelle, x, y, 1, "right")
			cutscene:wait(1)
			kris:setFacing("up")
			noelle:setFacing("up")
			cutscene:setSpeaker("susie")
			cutscene:text("* This door says, \"The Gateway Amidst Light and Dark\"...", "neutral_side") 
			cutscene:text("* That HAS to be it,[wait:5] right?", "neutral") 
			cutscene:text("* ...", "nervous") 
			cutscene:text("* Damn,[wait:5] looks like the door is locked...", "nervous_side") 
			cutscene:setSpeaker("susie")
			cutscene:text("* ...", "suspicious") 
			cutscene:wait(1.5)
			susie:setSprite("kick")
        	susie.sprite:play(0.1, loop)
			local rumble = Assets.playSound("impact")
			rumble:setLooping(true)
			cutscene:text("* IT WORKED BEFORE SO DON'T FAIL ME NOW!!!!", "teeth") 
			cutscene:wait(1.5)
			cutscene:wait(0.5)
			Game.world.music:fade(0, 1)
			cutscene:wait(1)
			Assets.stopSound("impact")
			susie:resetSprite()
			cutscene:wait(0.7)
			susie:setSprite("away_scratch")
        	susie.sprite:play(0.5, loop)
			cutscene:setSpeaker("susie")
			cutscene:text("* Well,[wait:5] that definitely didn't work.", "nervous_side") 
			susie:resetSprite()
			cutscene:text("* Hellllllloooo?[wait:10] Anybody thereeee?", "stupid") 
			cutscene:setSpeaker("omnis")
			Game.world.music:play("omnis")
			Game.world.music:fade(1, 1)
			cutscene:text("* Can you PLEASE just-", "mysterious")
			cutscene:text("* Oh.[wait:5] So YOU'RE the intruders...", "mysterious")
			cutscene:text("* ... I thought this was a much more elaborate plan by the police force.", "mysterious")
			cutscene:text("* ...", "mysterious")
			cutscene:text("* But I shall say,[wait:5] I am quite suprised.", "mysterious")
			cutscene:text("* I never thought anybody would be smart enough to use the device...", "mysterious")
			cutscene:text("* ... let alone turn off its transmitter.", "mysterious")
			cutscene:text("* However,[wait:5] I believe that was only luck.", "mysterious")
			cutscene:text("* And your luck ends here.", "mysterious")
			cutscene:text("* Behind this door lies the portal into the depths.", "mysterious")
			cutscene:text("* Which,[wait:5] as you've gone onto the device,[wait:5] you've read of them,[wait:5] right?", "mysterious")
			cutscene:text("* And that's what you're here for,[wait:5] isn't it?", "mysterious")
			cutscene:text("* Don't bother answering.[wait:5]\n* If you couldn't tell,[wait:5] those were rhetorical.", "mysterious")
			cutscene:text("* Now,[wait:5] if you don't mind,[wait:5] I have buisness to attend to.", "mysterious")
			cutscene:text("* So here's a piece of advice for you...", "mysterious")
			cutscene:text("* ... leave my shelter at once.", "mysterious")
			Game.world.music:fade(0, 1)
			cutscene:wait(1)
			Game.world.music:play("in-the-shelter")
			Game.world.music:fade(1, 1)
			cutscene:wait(1)
			cutscene:setSpeaker(susie)
			cutscene:text("* Damnit,[wait:5] that scientist REALLY just...", "annoyed")
			cutscene:text("* ...", "bangs_neutral")
			cutscene:text("* ... we should,[wait:5] uh,[wait:5] probably find another way into the gateway...", "annoyed_down")
			SetPlot("shelter_met_omnis")
			cutscene:attachFollowers()
		end
    end,

	devicetalk = function(cutscene)
		if not Plot:isBefore("shelter_heard_log") then
			cutscene:setSpeaker("susie")
			cutscene:text("* Let's go see if we can fix that Gateway,[wait:5] sound good,[wait:5] Kris?", "small_smile")
		end
	end
    }