return {

    device = function(cutscene)
		if Plot:isBefore("shelter_heard_log") then
			local kris = assert(cutscene:getCharacter("kris"))
			local susie = cutscene:getCharacter("susie") or kris
			local noelle = cutscene:getCharacter("noelle") or susie
			Kristal.Console:log("device_used")   
			cutscene:setSpeaker(susie)
			cutscene:text("* So...[wait:5] this is the device or whatever.", "nervous")
			cutscene:text("* Alright then,[wait:5] let's find out what the deal with this place is.", "nervous") 
			cutscene:wait(cutscene:fadeOut())
			Game.world.music:play("omnis")
			cutscene:wait(1)
			cutscene:setSpeaker()
			cutscene:text("[color:green]EXPERIMENT LOG 59: [wait:5] \nTHIS IS DR. OMNIS,[wait:5] ASSISTANT TO DR. G.")
			cutscene:text("[color:green]SINCE HIS DEATH,[wait:5] I'VE TAKEN CONTROL OVER THIS LAB.")
			cutscene:text("[color:green]WITH THAT RESPONSIBILITY,[wait:5] A NEW EXPERIMENT BEGINS.")
			cutscene:text("[color:green]THE DARK WORLD.[wait:5]\nA WORLD WHERE SHADOWS BLEND TOGETHER...")
			cutscene:text("[color:green]...TO CREATE SOMETHING BETTER.[wait:5] AN ILLUSION,[wait:5] YES,[wait:5]BUT...")
			cutscene:text("[color:green]IT MIGHT HELP THIS TOWN,[wait:5] MY HOMETOWN,[wait:5] IN FACT,[wait:5] OUR HOMETOWN,[wait:5] TO BE GREAT AGAIN.")
			cutscene:text("[color:green]I AM ALSO CREATING A KNIGHT.[wait:5] A ROARING KNIGHT.[wait:5] IT WILL PROTECT THESE WORLDS...") 
			cutscene:text("[color:green]...AND CREATE A BETTER FUTURE.[wait:5] I ALREADY HAVE A WILLING PARTICIPANT.[wait:5]IT BEGINS TOMORROW.")
			cutscene:text("[color:green]LET US SEE HOW THIS GOES.[wait:5] END LOG.")
			cutscene:text("[color:green]EXPERIMENT LOG 60: [wait:5]\nTHIS IS OMNIS...[wait:5]YOU CAN HEAR ME,[wait:5] CORRECT...?")
			cutscene:text("[color:green]EXCELLENT. NOW,[wait:5] NOT TO WORRY,[wait:5] THIS WILL BE QUICK.[wait:5] PLEASE STAY CALM.")
			cutscene:text("[color:green]I WILL NOT BE ABLE TO BROADCAST TO YOU AFTER THIS STARTS IN 3... 2... 1...")
			cutscene:text("[color:green]THIS EXPERIMENT...")
			cutscene:text("[color:green]IT WILL EXTRACT \"THE POWER\" FROM THIS PARTICIPANT.")
			cutscene:text("[color:green]HOWEVER,[wait:5] THAT POWER HAS YET TO BE NAMED...[wait:5] HE WASN'T ABLE TO COME UP WITH ONE BEFORE...")
			cutscene:text("[color:green]NO MATTER,[wait:5] ONCE THE POWER HAS BEEN EXTRACTED,[wait:5] IT WILL BE MADE STRONGER...")
			cutscene:text("[color:green]IT SEEMS TO BE STARTING...[wait:5] DESTROYING THE ORIGINAL SOUL...")
			cutscene:text("[color:green]W-[wait:5]WAIT,[wait:5] THAT'S NOT MEANT TO BE HAPPENING...[wait:5] HOW IS IT PERSISTING!?")
			cutscene:text("[color:green]NO,[wait:5] NO,[wait:5] NO![wait:5] THE MIND IS BECOMING CORRUPTED...[wait:5] IMMEDIATE GATEWAY BACKUP MADE...")
			cutscene:text("[color:green]I MUST SHUT THIS DOWN AND RESTORE THE ORIGINAL MIND...[wait:5] END LOG.")
			cutscene:text("[color:green]EXPERIMENT LOG 102:[wait:5] THIS IS DR. OMNIS.[wait:5] I'VE BEEN ABLE TO BROADCAST TO THIS MACHINE FROM...")
			cutscene:text("[color:green]THE DEPTHS...?[wait:5] THAT'S WHAT I HAVE CHOSEN TO CALL THEM,[wait:5] THAT IS.")
			cutscene:text("[color:green]IT IS...[wait:5] STRANGE,[wait:5] BUT AT LEAST I HAVE ACCESS TO THE GATEWAY MAIN CONTROLS.")
			cutscene:text("[color:green]I'M STILL LOOKING FOR DR. G,[wait:5] BUT NO LUCK YET...[wait:5] I'VE FOUND INFO ABOUT A VESSEL.")
			cutscene:text("[color:green]THIS WILL BE MY LAST LOG,[wait:5] AS I DO NOT WANT TO WASTE THIS MACHINE'S POWER.")
			cutscene:text("[color:green]I MUST CONTINUE MONITORING TO SEE WHO COMES INTO THE LABORATORIES... END LOG.")
			cutscene:wait(cutscene:fadeIn())
			cutscene:setSpeaker(susie)
			cutscene:text("* Hang on a second...[wait:5] that scientist said something about...", "sad")
			cutscene:text("* Monitoring who comes in here...[wait:5] damnit,[wait:5] that could mean-", "sad")
			cutscene:setSpeaker()
			Assets.playSound("phone")
			cutscene:wait(0.5)
			cutscene:text("[color:green]INCOMING BROADCAST...[wait:5] AUTOMATICALLY ACCEPTING...")
			Assets.playSound("item")
			cutscene:wait(0.3)
			cutscene:text("[color:green]THAT I'D KNOW... SMART GIRL,[wait:5] YOU ARE...[wait:5] VERY CLEVER...")
			cutscene:setSpeaker(noelle)
			cutscene:text("* Wh-[wait:5] what do you...[wait:5] want from us...?", "surprise_frown")
			cutscene:setSpeaker()
			cutscene:text("[color:green]WELL...[wait:5] THAT IS NO LONGER THE QUESTION,[wait:5] SWEET \"NOELLE.\"[wait:5] THE STORY OF DECEMBER TOLD OF THIS.")
			cutscene:setSpeaker(noelle)
			cutscene:text("* [speed:0.5][shake:1]HOW DO YOU KNOW ABOUT THAT...!?", "shock")
			cutscene:setSpeaker(susie)
			cutscene:text("* Look,[wait:5] whoever you are,[wait:5] leave her the hell alone!", "surprise_frown")
			cutscene:setSpeaker()
			cutscene:text("[color:green]IF YOU SAY SO,[wait:5] THE POWER OF THE SOUL SHOULD NOT BE MESSED WITH...")
			cutscene:text("[color:green]I WANTED YOU TO LEAVE MY SHELTER ALONE.[wait:5] THERE IS VERY CONFIDENTIAL INFORMATION HERE.")
			cutscene:text("[color:green]BUT NOW...[wait:5] YOU WILL PAY...[wait:5] BECAUSE WHAT YOU DON'T KNOW...")
			cutscene:text("[color:green][speed:0.2][shake:1]IS THAT YOU NEVER STOOD A CHANCE.[wait:5] GOODBYE!")
			cutscene:text("[color:green]BROADCAST HAS ENDED.[wait:5] NEW PROTOCOL REICIEVED.")
			cutscene:text("[color:red]ACTIVATING SHELTER PROTECTION PROTOCOL...[wait:5] ACCESSING DATA...")
			cutscene:text("[color:red]ERROR:[wait:5] POWER LEVEL AT 1%.[wait:5] GATEWAY:[wait:5] ON LOCKDOWN.[wait:5] WORLD STATUS:[wait:5] UNSTABLE.[wait:5] POWERING OFF...")
			Game.world.music:fade(0, 1)
			cutscene:wait(1)
			Game.world.music:play("in-the-shelter")
			Game.world.music:fade(1, 1)
			cutscene:setSpeaker(susie)
			cutscene:text("* Hey,[wait:5] Noelle,[wait:5] you okay?", "sad")
			cutscene:setSpeaker(noelle)
			cutscene:text("* Yeah...[wait:5] I'll be fine...[wait:5] it just spooked me a bit...", "sad_smile_b")
			cutscene:setSpeaker(susie)
			cutscene:text("* Hang on a second...[wait:5] The machine said something about...", "neutral_side")
			cutscene:text("* ...a Gateway...?[wait:5] If we could fix that Gateway...", "neutral")
			cutscene:text("* We could probably stop that damn scientist![wait:5] Yeah!", "surprise_smile")
			SetPlot("shelter_heard_log")
			Game:getQuest("shelter"):complete()
			Game:getQuest("gateway"):unlock()
		else 
			cutscene:setSpeaker("susie")
			cutscene:text("* Let's fix that Gateway,[wait:5] Kris.", "nervous_side")
		end;
    end,

    }