return {

    UNUSED = function(cutscene)
        cutscene:text("* im december im decembering it.") 
    end,
    dessroom = function(cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* Hey...[wait:5] uhh...[wait:5] that rooms off-limits,[wait:5] faha...", "smile_side") 
    end,
    basement = function(cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* K-[wait:5]Kris...?[wait:5] Why do you wanna go into the basement?", "surprise_smile_b") 
        cutscene:text("* Is that really exciting to you!?[wait:5] Fahaha!!!", "smile_closed") 
        cutscene:setSpeaker(susie)
        cutscene:text("* Hey,[wait:5] it's not locked,[wait:5] right?[wait:5] I wanna go down there!", "sincere_smile") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* Fahaha![wait:5] It's not locked.[wait:5] If you REALLY wanna go down there,[wait:5] I'll come.", "smile")
        Assets.playSound("dooropen")
        Game.world:mapTransition("noelles house/basement/basement")
    end,
    noelleroom = function(cutscene, event)
        cutscene:text("* Are you sure you want to go to Noelle's room to hang out?")
        if cutscene:choicer({ "Yes", "No" }) == 1 then
            local kris = assert(cutscene:getCharacter("kris"))
            local noelle = cutscene:getCharacter("noelle")
            local susie = cutscene:getCharacter("susie")
            Assets.playSound("dooropen")
            cutscene:fadeOut(0.5, { music = true })
            cutscene:wait(2)
            cutscene:detachFollowers()
            cutscene:wait(cutscene:mapTransition("noelles house/noelle room"))
            cutscene:wait(0.5)
            local kris = assert(cutscene:getCharacter("kris"))
            local noelle = cutscene:getCharacter("noelle")
            local susie = cutscene:getCharacter("susie")
            cutscene:detachFollowers()
            cutscene:fadeIn(1)
            kris:setFacing("left")
            susie:setFacing("left")
            noelle:setFacing("left")
            cutscene:wait(0.7)
            cutscene:walkTo(kris, "kris1", 2)
            cutscene:walkTo(susie, "susie1", 2)
            cutscene:walkTo(noelle, "noelle1", 2)
            cutscene:setSpeaker(susie)
            cutscene:text("* Damn,[wait:5] Noelle,[wait:5] you uh... got a nice room.", "stupid")
            cutscene:setSpeaker(noelle)
            cutscene:text("* T-Thanks Susie![wait:5] Get as comfy as you want!", "blush_finger")
            Game.world.music:fade(1, 1)
            cutscene:wait(0.5)
            Assets.playSound("wing")
            cutscene:shakeCharacter(susie)
            cutscene:shakeCharacter(noelle)
            susie:setPosition(Game.world.map:getMarker("susie2"))
            noelle:setPosition(Game.world.map:getMarker("noelle2"))
            susie:setSprite("sit")
            noelle:setSprite("sitdown_bed")
            Game.world.music:play("noellehouse")
            Game.world.music:fade(1, 1)
            cutscene:setSpeaker(noelle)
            cutscene:text("* So,[wait:5] what'd you want to talk to me about?", "blush_smile_closed")
            cutscene:setSpeaker(susie)
            cutscene:text("* Oh,[wait:5] yeah,[wait:5] almost forgot about that...", "stupid")
            cutscene:setSpeaker(noelle)
            cutscene:text("* T-That's alright!", "blush_surprise_smile")
            cutscene:setSpeaker(susie)
            cutscene:text("* So...[wait:5] uh...[wait:5] I found something pretty bad.", "shock_nervous")
            cutscene:text("* Y'know the earthquakes we've been having lately?", "sad")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Yeah,[wait:5] they keep catching me offguard...[wait:5] Fahaha!", "blush_smile")
            cutscene:setSpeaker(susie)
            cutscene:text("* Yeah,[wait:5] well,[wait:5] I went south of town...", "shy_down")
            cutscene:text("* And I found the shelter.", "shy")
            cutscene:text("* Y'know,[wait:5] the one the knight talked about?", "sincere")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Yeah...[wait:5] they really gave me the creeps...", "dejected")
            cutscene:setSpeaker(susie)
            cutscene:text("* Well...[wait:5] uh...[wait:5] the doors to the shelter are open...", "sus_nervous")
            cutscene:text("* But on the bright side,[wait:5] we plan to explore it,[wait:5] and stuff...", "smile")
            cutscene:setSpeaker(noelle)
            cutscene:text("* So,[wait:5] you want me to come with you guys...?", "confused")
            cutscene:setSpeaker(susie)
            cutscene:text("* Yeah![wait:5] We've just gotta gather some supplies and get in there!", "sus_nervous")
            cutscene:text("* And there won't be any dark worlds,[wait:5] since that the knight is gone.", "smirk")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Well then,[wait:5] why not?[wait:5] I'll come with you guys!", "blush_smile")
            cutscene:setSpeaker(susie)
            cutscene:text("* Hell yeah![wait:5] We've just gotta get some stuff at my apartment.", "sincere_smile")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Sounds good,[wait:5] S-Susie!", "blush_big_smile")
            Assets.playSound("wing")
            Game.world.music:fade(0, 1)
            cutscene:shakeCharacter(susie)
            cutscene:shakeCharacter(noelle)
            kris:resetSprite()
            noelle:resetSprite()
            susie:resetSprite()
            kris:setFacing("right")
            susie:setFacing("right")
            noelle:setFacing("right")
            susie:setPosition(Game.world.map:getMarker("susie1"))
            noelle:setPosition(Game.world.map:getMarker("noelle1"))
            cutscene:walkTo(kris, "outsideofmap", 5)
            cutscene:walkTo(susie, "outsideofmap", 5)
            cutscene:walkTo(noelle, "outsideofmap", 5)
            cutscene:fadeOut(1.5, { music = true })
            cutscene:wait(2)
            cutscene:attachFollowers()
            cutscene:loadMap("hometown/town_north", 480, 344)
            Game.world.music:play("hometown")
            cutscene:wait(cutscene:fadeIn(1, { music = true }))
        else
            cutscene:text("* You decided to hold off on the hangout for now.")
        end
    end,
    parentroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* This is my parent's room,[wait:5] not mine!", "confused_surprise_b") 
    end,
    bathroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(susie)
        cutscene:text("* That's the bathroom,[wait:5] Kris...", "stupid") 
    end,
    workroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* There's uh...[wait:5] really sensitive stuff in there...", "frown") 
        cutscene:text("* Let's just hang out in my room,[wait:5] alright?", "smile_closed") 
    end,
    fridge = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:text("* It's a fridge.[wait:5] There's a hand-drawn mothers day picture hung on.") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* My sis made that...[wait:5] mom still looks at it every day... fahaha...", "sad_smile_b") 
        cutscene:setSpeaker(susie)
        cutscene:text("* H-[wait:5]Hey,[wait:5] Noelle,[wait:5] you don't have to cry...", "shy_down") 
        cutscene:text("* It'll be okay...[wait:5] look![wait:5] We're smiling![wait:5] Haha!", "susie_dream_grin")
    end,
    sitdown = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:text("* It's a fridge.[wait:5] There's a hand-drawn mothers day picture hung on.") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* My sis made that...[wait:5] mom still looks at it every day... fahaha...", "sad_smile_b") 
        cutscene:setSpeaker(susie)
        cutscene:text("* H-[wait:5]Hey,[wait:5] Noelle,[wait:5] you don't have to cry...", "shy_down") 
        cutscene:text("* It'll be okay...[wait:5] look![wait:5] We're smiling![wait:5] Haha!", "susie_dream_grin")
    end,
}