return {

    UNUSED = function(cutscene)
        cutscene:text("* im december im decembering it.") 
    end,
    dessroom = function(cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* Hey...[wait:5] uhh...[wait:5] that rooms off-limits,[wait:5] fahaha...", "smile_side") 
        cutscene:setSpeaker(susie)
        cutscene:text("* (Kris,[wait:5] we should leave this one be...)", "sus_nervous")
    end,
    basement = function(cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* K-[wait:5]Kris...?[wait:5] Why do you wanna go into the basement?", "surprise_smile_b") 
        cutscene:text("* Is that really exciting to you!?[wait:5] Fahaha!!!", "smile_closed") 
        cutscene:setSpeaker(susie)
        cutscene:text("* Hey,[wait:5] it's not locked,[wait:5] right?[wait:5] I wanna go down there!", "sincere_smile") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* Fahaha![wait:5] It's not locked.[wait:5] If you REALLY wanna go down there,[wait:5] I'll come.", "smile")
        Assets.playSound("dooropen")
        Game.world:mapTransition("noelles house/basement/basement")
    end,
    noelleroom = function(cutscene, event)
        cutscene:text("* Are you sure you want to go to Noelle's room to hang out?")
        if cutscene:choicer({ "Yes", "No" }) == 1 then
            local kris = assert(cutscene:getCharacter("kris"))
            local noelle = cutscene:getCharacter("noelle")
            local susie = cutscene:getCharacter("susie")
            Assets.playSound("dooropen")
            cutscene:fadeOut(0.5, { music = true })
            cutscene:wait(2)
            cutscene:detachFollowers()
            cutscene:wait(cutscene:mapTransition("noelles house/noelle room"))
            cutscene:wait(0.5)
            local kris = assert(cutscene:getCharacter("kris"))
            local noelle = cutscene:getCharacter("noelle")
            local susie = cutscene:getCharacter("susie")
            cutscene:detachFollowers()
            cutscene:fadeIn(1)
            kris:setFacing("left")
            susie:setFacing("left")
            noelle:setFacing("left")
            cutscene:wait(0.7)
            cutscene:walkTo(kris, "kris1")
            cutscene:walkTo(susie, "susie1")
            cutscene:walkTo(noelle, "noelle1")
            cutscene:setSpeaker(susie)
            cutscene:text("* Damn,[wait:5] Noelle,[wait:5] you uh... got a nice room.", "stupid")
            cutscene:setSpeaker(noelle)
            cutscene:text("* T-Thanks Susie![wait:5] Get as comfy as you want!", "blush_finger")
            Game.world.music:fade(1, 1)
            cutscene:wait(0.5)
            Assets.playSound("wing")
            cutscene:shakeCharacter(susie)
            cutscene:shakeCharacter(noelle)
            susie:setPosition(Game.world.map:getMarker("susie2"))
            noelle:setPosition(Game.world.map:getMarker("noelle2"))
            susie:setSprite("sit")
            noelle:setSprite("sitdown_bed")
            Game.world.music:play("noellehouse")
            Game.world.music:fade(1, 1)
            cutscene:setSpeaker(noelle)
            cutscene:text("* So,[wait:5] what'd you want to talk to me about?", "blush_smile_closed")
            cutscene:setSpeaker(susie)
            cutscene:text("* Oh,[wait:5] yeah,[wait:5] almost forgot about that...", "stupid")
            cutscene:setSpeaker(noelle)
            cutscene:text("* T-That's alright!", "blush_surprise_smile")
            cutscene:setSpeaker(susie)
            cutscene:text("* So...[wait:5] uh...[wait:5] basically I found something pretty bad.", "shock_nervous")
            cutscene:text("* Y'know the earthquakes we've been having lately?", "sad")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Yeah,[wait:5] they keep catching me offguard...[wait:5] Fahaha!", "blush_smile")
            cutscene:setSpeaker(susie)
            cutscene:text("* Yeah,[wait:5] well,[wait:5] I went south of town,[wait:5] well,[wait:5] VERY south of town.", "shy_down")
            cutscene:text("* And I found the shelter...", "shy")
            cutscene:text("* Y'know,[wait:5] the one the knight talked about?", "sincere")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Yeah...[wait:5] really gave me the creeps when you told me about them...", "dejected")
            cutscene:setSpeaker(susie)
            cutscene:text("* Well...[wait:5] uh...[wait:5] there's no easy way to say this but...", "sus_nervous")
            cutscene:text("* [shake:1]The doors to the shelter are open...", "sad")
            cutscene:text("* But anyway,[wait:5] we wouldn't want you to...[wait:5] miss out on anything...[wait:5] so...", "smile")
            cutscene:setSpeaker(noelle)
            cutscene:text("* So,[wait:5] another adventure...?", "confused")
            cutscene:setSpeaker(susie)
            cutscene:text("* Yeah![wait:5] Except,[wait:5] uh... probably different.", "sus_nervous")
            cutscene:text("* Because,[wait:5] it didn't look like there was dark world in there...", "smirk")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Then why do you want me to come,[wait:5] ", "question")
            cutscene:text("* It's probably only an old shelter with creepy lights! Fahaha!", "question")
            cutscene:setSpeaker(susie)
            cutscene:text("* Well who knows,[wait:5] maybe we'll find some cool collectables in there!", "closed_grin")
            cutscene:text("* And don't you just wanna find out the bottom of this mystery already!?", "nervous_side")
            cutscene:setSpeaker(noelle)
            cutscene:text("* Well,[wait:5] alright...[wait:5] I'll come!", "blush_smile")
            cutscene:setSpeaker(susie)
            cutscene:text("* Hell yeah![wait:5] We just gotta make a quick stop by my apartment,[wait:5] okay?", "sincere_smile")
            cutscene:setSpeaker(noelle)
            cutscene:text("* O-Okay!", "blush_big_smile")
            Assets.playSound("wing")
            Game.world.music:fade(0, 1)
            cutscene:shakeCharacter(susie)
            cutscene:shakeCharacter(noelle)
            kris:resetSprite()
            noelle:resetSprite()
            susie:resetSprite()
            kris:setFacing("right")
            susie:setFacing("right")
            noelle:setFacing("right")
            susie:setPosition(Game.world.map:getMarker("susie1"))
            noelle:setPosition(Game.world.map:getMarker("noelle1"))
            cutscene:walkTo(kris, "outsideofmap", 10)
            cutscene:walkTo(susie, "outsideofmap", 10)
            cutscene:walkTo(noelle, "outsideofmap", 10)
            cutscene:fadeOut(1.5, { music = true })
            cutscene:wait(1.5)
            cutscene:attachFollowers()
            cutscene:mapTransition("hometown/town_north", 480, 344)
            Game.world.music:play("hometown")
            cutscene:wait(cutscene:fadeIn(1, { music = true }))
            Game:getQuest("getnoelle"):complete()
            Game:getQuest("supplies"):unlock()
        else
            cutscene:text("* You decided to hold off on the hangout for now.")
        end
    end,
    parentroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(susie)
        cutscene:text("* So,[wait:5] this is your parent's room,[wait:5] right?", "stupid") 
        cutscene:text("* Your moms not home,[wait:5] is she?", "nervous_side") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* Nope![wait:5] Haha...[wait:5] I haven't seen for a while...", "sad_smile") 
        cutscene:setSpeaker(susie)
        cutscene:text("* Well,[wait:5] in THAT case,[wait:5] can we go in there?", "sincere_smile") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* Let's just leave it be,[wait:5] wouldn't want mom mad,[wait:5] fahaha!", "smile_closed_b") 
        cutscene:text("* (And I want it nice and clean for when dad gets home tomorrow...)", "smile_closed_b") 
    end,
    bathroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(susie)
        cutscene:text("* Y'know,[wait:5] I'm pretty suspicious of this door...", "stupid") 
        cutscene:text("* I never saw what it was last time I was over,[wait:5] what is it?", "nervous") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* That's uh...[wait:5] a bathroom.", "blush_surprise_smile") 
        cutscene:setSpeaker(susie)
        cutscene:text("* Damnit!", "teeth") 
    end,
    workroom = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:setSpeaker(noelle)
        cutscene:text("* There's uh...[wait:5] really sensitive stuff in there...", "frown") 
        cutscene:text("* Let's just hang out in my room,[wait:5] alright?", "smile_closed") 
    end,
    fridge = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:text("* It's a fridge.[wait:5] There's a hand-drawn mothers day picture hung on.") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* My sis made that...[wait:5] mom still looks at it every day... fahaha...", "sad_smile_b") 
        cutscene:setSpeaker(susie)
        cutscene:text("* H-[wait:5]Hey,[wait:5] Noelle,[wait:5] you don't have to cry...", "shy_down") 
        cutscene:text("* It'll be okay...[wait:5] look![wait:5] We're smiling![wait:5] Haha!", "susie_dream_grin")
    end,
    sitdown = function (cutscene)
        local noelle = cutscene:getCharacter("noelle")
        local susie = cutscene:getCharacter("susie")
        cutscene:text("* It's a fridge.[wait:5] There's a hand-drawn mothers day picture hung on.") 
        cutscene:setSpeaker(noelle)
        cutscene:text("* My sis made that...[wait:5] mom still looks at it every day... fahaha...", "sad_smile_b") 
        cutscene:setSpeaker(susie)
        cutscene:text("* H-[wait:5]Hey,[wait:5] Noelle,[wait:5] you don't have to cry...", "shy_down") 
        cutscene:text("* It'll be okay...[wait:5] look![wait:5] We're smiling![wait:5] Haha!", "susie_dream_grin")
    end,
}