return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 23,
  height = 10,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 60,
  properties = {
    ["light"] = true,
    ["music"] = "in-the-shelter"
  },
  tilesets = {},
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 10,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "imagelayer",
      image = "../../../../assets/sprites/backgrounds/mainroom.png",
      id = 2,
      name = "mainroom",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 120,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 255.5,
          y = 102.5,
          width = 152,
          height = 41.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 408,
          y = 81,
          width = 280.5,
          height = 42.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 77,
          y = 349,
          width = 310,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 380.5,
          y = 364.5,
          width = 173,
          height = 34.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 551.5,
          y = 349.5,
          width = 272.5,
          height = 14.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 827,
          y = 132,
          width = 25.5,
          height = 133.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 147,
          y = 105.5,
          width = 19.5,
          height = 100.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 230.023,
          y = 37.6498,
          width = 84,
          height = 108.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "polygon",
          x = 689.787,
          y = 143.519,
          width = 44.1227,
          height = 11.3073,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 1.213, y = -23.5191 },
            { x = 43.213, y = 15.9809 },
            { x = 15.6173, y = -10.7042 },
            { x = 5.15523, y = -19.4485 }
          },
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "polygon",
          x = 781.75,
          y = 289.25,
          width = 145.5,
          height = 37.5,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 4, y = -78 },
            { x = 142.5, y = 53 },
            { x = 51.5, y = -35.5 },
            { x = 17, y = -64.5 }
          },
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "polygon",
          x = 693.75,
          y = 160.25,
          width = 145.5,
          height = 37.5,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 4, y = -78 },
            { x = 142.5, y = 53 },
            { x = 51.5, y = -35.5 },
            { x = 17, y = -64.5 }
          },
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120.432,
          y = 213.205,
          width = 15.1364,
          height = 46.6818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 135.705,
          y = 198.841,
          width = 15.1364,
          height = 46.6818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 150.977,
          y = 182.659,
          width = 15.1364,
          height = 46.6818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152.795,
          y = 169.932,
          width = 15.1364,
          height = 46.6818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 207.159,
          y = 126.477,
          width = 15.1364,
          height = 46.6818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220.977,
          y = 113.023,
          width = 15.1364,
          height = 46.6818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 111,
          y = 261,
          width = 14.5,
          height = 86,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 821.25,
          y = 258.75,
          width = 8,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 192.468,
          y = 136.3,
          width = 38.5,
          height = 64.1781,
          rotation = 46.0159,
          visible = true,
          properties = {
            ["map"] = "shelter/awakening",
            ["marker"] = "awakeningdoor"
          }
        },
        {
          id = 35,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 725.507,
          y = 158.241,
          width = 35.3229,
          height = 81.5,
          rotation = 317.208,
          visible = true,
          properties = {
            ["map"] = "shelter/hallway"
          }
        },
        {
          id = 40,
          name = "cameratarget",
          type = "",
          shape = "rectangle",
          x = -0.666667,
          y = -15.2727,
          width = 920.667,
          height = 416.667,
          rotation = 0,
          visible = false,
          properties = {
            ["lockx"] = false,
            ["locky"] = true,
            ["marker"] = "camfocus",
            ["time"] = 0.1
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "spawn",
          type = "",
          shape = "point",
          x = 470.14,
          y = 334.617,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "mainroomdoor",
          type = "",
          shape = "point",
          x = 698.5,
          y = 211.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "camfocus",
          type = "",
          shape = "point",
          x = 470,
          y = 184,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "awaken",
          type = "",
          shape = "point",
          x = 253,
          y = 214.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
